# Generated by Django 4.1.4 on 2022-12-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_name_quote_quote_name_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiondata',
            name='total_vote',
        ),
        migrations.CreateModel(
            name='ElectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('presidential', 'Presidential'), ('governorship', 'Governorship')], max_length=30, verbose_name='Election Type')),
                ('date_of_election', models.IntegerField()),
                ('area_type', models.CharField(default='county', max_length=6, verbose_name='Area Type')),
                ('area_name', models.CharField(max_length=255, verbose_name='Area Name')),
                ('election_notes', models.TextField(verbose_name='Election Notes')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.state')),
            ],
        ),
    ]
