# Generated by Django 4.1.4 on 2022-12-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_electiondata_total_vote_electionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiondata',
            name='total_vote',
            field=models.IntegerField(null=True),
        ),
    ]
