# Generated by Django 4.1.4 on 2022-12-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_alter_electiondata_candidate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electiondata',
            options={'ordering': ['-date_of_election', '-total_vote']},
        ),
    ]
