# Generated by Django 4.1.4 on 2022-12-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_alter_electiondata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondata',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='election.candidate'),
        ),
        migrations.AlterField(
            model_name='electiondata',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='election.party'),
        ),
        migrations.AlterField(
            model_name='electionnote',
            name='election_notes',
            field=models.TextField(null=True, verbose_name='Election Notes'),
        ),
    ]
