# Generated by Django 4.1.4 on 2023-01-05 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0007_alter_electiondata_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state",
                to="election.state",
            ),
        ),
    ]
