# Generated by Django 4.1.5 on 2023-01-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0008_alter_county_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["candidate_name"]},
        ),
        migrations.AlterModelOptions(
            name="county",
            options={"ordering": ["county_name"], "verbose_name_plural": "Counties"},
        ),
        migrations.AlterModelOptions(
            name="electiondata",
            options={
                "ordering": ["-date_of_election", "-total_vote"],
                "verbose_name_plural": "Election Data",
            },
        ),
        migrations.AlterModelOptions(
            name="electionnote",
            options={"verbose_name_plural": "Election Notes"},
        ),
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ["party_name"], "verbose_name_plural": "Parties"},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["state_name"], "verbose_name_plural": "States"},
        ),
    ]
