name: Automatic Rebase
on:
  workflow_run:
    workflows: ["Django CI"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: dependencies
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git rebase origin/main
        git push origin dependencies --force
#   rebase:
#     name: Rebase `dependencies` to `main`
#     runs-on: ubuntu-latest
